name: Publish NuGet Packages

on:
  push:
    paths:
      - "core/**"
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
          source-url: https://nuget.pkg.github.com/${{ github.actor }}/index.json

      - name: Pack NuGet Packages
        run: |
          dotnet pack core/src/ELibrary.Core.EF --output ./nupkg --configuration Release
          dotnet pack core/src/ELibrary.Core.ElasticSearch --output ./nupkg --configuration Release

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push ./nupkg/*.nupkg --source https://nuget.pkg.github.com/${{ github.actor }}/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
