version: '3.8'

services:
  elibrary.users:
    build:
      context: .
      dockerfile: ELibrary.Users/Dockerfile
    image: elibrary.users.publicapi
    ports:
      - "8081:8080"
    networks:
      - elibrary_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver

  elibrary.orders:
    build:
      context: .
      dockerfile: ELibrary.Orders/src/Dockerfile
    image: elibrary.orders.publicapi
    ports:
      - "8082:8080"
    networks:
      - elibrary_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - UserService__BaseUrl=http://elibrary.users:8080
      - BookService__BaseUrl=http://elibrary.books:8080
      - LOG_LEVEL=Information
    depends_on:
      - elibrary.users

  elibrary.books:
    build:
      context: .
      dockerfile: ELibrary.Books/Dockerfile
    image: elibrary.books.publicapi
    ports:
      - "8083:8080"
    networks:
      - elibrary_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ElasticSearch__Url=http://elasticsearch:9200
    depends_on:
      - elibrary.users
      - elasticsearch
  
  elibrary.consumers.elasticservice:
    build:
      context: .
      dockerfile: ELibrary.Consumers/src/Dockerfile_ElasticService
    image: elibrary.consumers.elasticservice
    ports:
      - "8084:80"
    networks:
      - elibrary_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BookService__BaseUrl=http://elibrary.books:8080
    depends_on:
      - rabbitmq

  elibrary.consumers.book:
    build:
      context: .
      dockerfile: ELibrary.Consumers/src/Dockerfile_Book
    image: elibrary.consumers.book
    ports:
      - "8085:80"
    networks:
      - elibrary_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BookService__BaseUrl=http://elibrary.books:8080
    depends_on:
      - rabbitmq  

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Lorik.1234
    ports:
      - "1434:1433"
    networks:
      - elibrary_network
    container_name: sqlserver-container
    volumes:
      - sqlserver_data:/var/opt/mssql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=12345
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elibrary_network
    volumes:
      - es_data:/usr/share/elasticsearch/data

  rabbitmq:
    image: rabbitmq:3.10-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - elibrary_network

networks:
  elibrary_network:
    driver: bridge

volumes:
  es_data:
  sqlserver_data:
