# global:
#   scrape_interval: 10s

# scrape_configs:
#   - job_name: 'otel-collector'
#     static_configs:
#       - targets: ['otel-collector:8889']

global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'elibrary.books'
    static_configs:
      - targets: ['elibrary.books:8083']  # ✅ Scrape directly from BooksMS
