FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY ["ELibrary.Shared/src/ELibrary.Contracts", "ELibrary.Shared/src/ELibrary.Contracts/"]
COPY ["ELibrary.Consumers/src/ELibrary.Consumers.Book", "ELibrary.Consumers/src/ELibrary.Consumers.Book/"]

RUN dotnet restore "ELibrary.Consumers/src/ELibrary.Consumers.Book/ELibrary.Consumers.Book.csproj"

WORKDIR "/src/ELibrary.Consumers/src/"
RUN dotnet build "ELibrary.Consumers.Book/ELibrary.Consumers.Book.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ELibrary.Consumers.Book/ELibrary.Consumers.Book.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=publish /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", "ELibrary.Consumers.Book.dll"]
