name: Publish NuGet Packages

on:
  push:
    paths:
      - "ELibrary.Core/**"
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Calculate Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
          source-url: https://nuget.pkg.github.com/${{ github.actor }}/index.json

      - name: Update NuGet Package Versions
        run: |
          sed -i 's/<Version>.*<\/Version>/<Version>${{ steps.gitversion.outputs.SemVer }}<\/Version>/' ELibrary.Core/src/ELibrary.Core.EF/ELibrary.Core.EF.csproj
          sed -i 's/<Version>.*<\/Version>/<Version>${{ steps.gitversion.outputs.SemVer }}<\/Version>/' ELibrary.Core/src/ELibrary.Core.ElasticSearch/ELibrary.Core.ElasticSearch.csproj

      - name: Pack NuGet Packages
        run: |
          dotnet pack ELibrary.Core/src/ELibrary.Core.EF --output ./nupkg --configuration Release
          dotnet pack ELibrary.Core/src/ELibrary.Core.ElasticSearch --output ./nupkg --configuration Release

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push ./nupkg/*.nupkg --source https://nuget.pkg.github.com/${{ github.actor }}/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
